---
title: "Final project"
date: "2019-04-23"
due_date: "2019-04-23"
due_time: "11:59 PM"
editor_options: 
  chunk_output_type: console
output:
  blogdown::html_page:
    css: /css/gt-overrides.css
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

For your final project, you will perform some (hypothetical) economic analyses and use your newfound vocabulary and skills to make a recommendation. 

You will submit two files on Learning Suite:

1. A PDF of of a 2–3-page memo
2. An Excel file with your technical appendix

You will be graded based on the rubric posted linked below. Though there are correct answers for the different market equilibria and the differential effects of taxes across states and firms, *there is no one correct recommendation*. Accordingly, I am not looking for a predetermined recommendation in your memos. Instead, I'm looking for good justification for why you make your recommendation, given your math and other calculations.

You must turn in your own memo and technical appendix, but you can (and should!) work with others to complete the calculations. You can work in groups of up to five people. When turning in your assignment on Learning Suite, use the notes field to indicate who you worked with.

Here are all the materials you'll need:

- [<i class="far fa-file-pdf"></i> Project instructions and details](/files/mpa612_w19_final-project.pdf)
- [<i class="fas fa-file-excel"></i> Sample workbook](/files/sample-workbook-fixed.xlsx)
- [<i class="fas fa-file-excel"></i> Rubric](/files/final-project-rubric.xlsx)

**This project is due by 11:59 PM on Tuesday, April 23, 2019.** No late work will be accepted.

Good luck!
